import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Tyler Schock.27
 *
 */
public final class RSSAggregator {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSAggregator() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel") : ""
                + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        //Extract channel child title
        XMLTree title = channel.child(getChildElement(channel, "title"));
        int titleChild = title.numberOfChildren();
        String titleLabel = "No Title";
        if (titleChild > 0) {
            titleLabel = title.child(0).label();
        }

        //Extract channel child link
        XMLTree link = channel.child(getChildElement(channel, "link"));
        String linkLabel = link.child(0).label();

        //Extract channel child description
        XMLTree descrip = channel
                .child(getChildElement(channel, "description"));
        int descripChild = descrip.numberOfChildren();
        String descripLabel = "No Description";
        if (descripChild > 0) {
            descripLabel = descrip.child(0).label();
        }

        /*
        *
        */
        out.println("<html> <head> <title>" + titleLabel + "</title>");
        out.println("</head> <body>");
        out.println(
                "<h1> <a href =" + linkLabel + ">" + titleLabel + "</a> </h1>");
        out.println("<p>");
        out.println(descripLabel);
        out.println("</p>");
        out.println("<table border=\"1\">");
        out.println("<tr>");
        out.println("<th>\"Date\"</th>");
        out.println("<th>\"Source\"</th>");
        out.println("<th>\"News\"</th>");
        out.println("</tr>");
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("</table>");
        out.println("</body> </html>");

    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        int childIndex = -1;
        int children = xml.numberOfChildren();
        int i = 0;

        while (i < children) {

            if (xml.child(i).label().equals(tag)) {
                childIndex = i;
            }

            i++;
        }
        return childIndex;

    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item") : ""
                + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("<tr>");

        /*
         * check for pubDate
         */
        int i = getChildElement(item, "pubDate");
        if (i == -1) {
            out.println("<td>No date available</td>");
        } else {
            String date = item.child(i).child(0).label();
            out.println("<td>" + date + "</td>");
        }

        /*
         * check for source if source is extracted, get url
         */
        i = getChildElement(item, "source");
        if (i == -1) {
            out.println("</td>No source available</td>");
        } else {
            int linkChild = item.child(i).numberOfChildren();
            if (linkChild > 0) {
                String url = item.child(i).child(0).label();
                String source = item.child(i).child(0).label();
                out.println(
                        "<td><a href =  " + url + ">" + source + "</a></td>");
            }
        }

        /*
         * check for title, description, or both if either or both is extracted
         * is extracted, get link for table
         */
        i = getChildElement(item, "title");
        String descrip = "No description";
        String title = "No title";
        String titleUrl = "";
        String descripUrl = "";
        if (i == -1 || i > 0) {
            int j = getChildElement(item, "description");
            int descripChild = item.child(j).numberOfChildren();
            if (descripChild > 0) {
                int h = getChildElement(item, "link");
                if (h > 0) {
                    descripUrl = item.child(h).child(0).label();
                    descrip = item.child(j).child(0).label();
                    out.println("<td><a href =" + descripUrl + ">" + descrip
                            + "</a></td>");
                } else {

                    out.println("<td>" + descrip + "</td>");
                }
            }

        } else {
            int titleChild = item.child(i).numberOfChildren();
            if (titleChild > 0) {
                int j = getChildElement(item, "link");
                if (j > 0) {
                    titleUrl = item.child(j).child(0).label();
                    title = item.child(i).child(0).label();
                    out.println("<td><a href =" + titleUrl + ">" + title
                            + "</a></td>");
                } else {
                    out.println("<td>" + title + "</td>");
                }
            }
        }
        out.println("</tr>");

    }

    /**
     * Processes one XML RSS (version 2.0) feed from a given URL converting it
     * into the corresponding HTML output file.
     *
     * @param url
     *            the URL of the RSS feed
     * @param file
     *            the name of the HTML output file
     * @param out
     *            the output stream to report progress or errors
     * @updates out.content
     * @requires out.is_open
     * @ensures <pre>
     * [reads RSS feed from url, saves HTML document with table of news items
     *   to file, appends to out.content any needed messages]
     * </pre>
     */
    private static void processFeed(String url, String file, SimpleWriter out) {
        XMLTree xml = new XMLTree1(url);
        SimpleWriter outFile = new SimpleWriter1L(file);

        XMLTree channel = xml.child(0);

        // SimpleWriter fileOut = SimpleWriter1L();

        /*
         * Output Header
         */
        outputHeader(channel, outFile);

        /*
         * Iterate through item elements to print to table
         */
        int i = 0;
        while (i < channel.numberOfChildren()) {
            if (channel.child(i).label().equals("item")) {
                processItem(channel.child(i), outFile);
            }
            i++;
        }

        /*
         * output footer
         */
        outputFooter(outFile);
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        /*
         * Input the source URL.
         */
        out.print("Enter the URL of an RSS 2.0 news feed: ");
        String feed = in.nextLine();
        /*
         * Read XML input and initialize XMLTree. If input is not legal XML,
         * this statement will fail.
         */
        XMLTree xml = new XMLTree1(feed);

        /*
         * Input file
         */
        out.println("Enter a file with its .html extension: ");
        String source = in.nextLine();
        SimpleWriter file = new SimpleWriter1L(source);

        /*
         * Create index page
         */
        String title = xml.attributeValue("title");
        file.print("<html> <head> <title>" + title
                + "</title> </head> <body> <head>" + "<h1>" + title
                + " </h1> </head>" + "<ul>");
        int j = 0;
        while (j < xml.numberOfChildren()) {
            String name = xml.child(j).attributeValue("name");
            String fileName = xml.child(j).attributeValue("file");
            file.print("<li> <p> <a href=" + fileName + ">" + name + "</a>"
                    + "</p>" + "</li>");
            j++;
        }

        int i = 0;
        while (i < xml.numberOfChildren()) {
            String fileName = xml.child(i).attributeValue("file");
            String url = xml.child(i).attributeValue("url");
            processFeed(url, fileName, out);
            i++;
        }

        file.print("</ul> </body> </html>");

        in.close();
        out.close();
        file.close();
    }

}
